# Common versions
node_exporter_version: "1.9.1"
postgres_exporter_version: "0.17.1"
prometheus_version: "3.3.0"
grafana_version: "11.6.1"

arch: "linux-amd64"
prometheus_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

# Common Patroni settings
patroni_scope: demo
patroni_api_port: 8008
patroni_ttl: 30
patroni_loop_wait: 10
patroni_retry_timeout: 10
patroni_max_lag: 1048576
patroni_use_pg_rewind: true
patroni_use_slots: true
patroni_config: "/etc/patroni.yml"

# etcd settings
etcd_client_port: 2379

# PostgreSQL settigns
pg_version: 16
data_dir: "/var/lib/postgresql/{{ pg_version }}/main"
postgresql_version: 16
postgresql_encoding: UTF8
postgresql_port: 5432
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_dir: "/usr/lib/postgresql/{{ postgresql_version }}/bin"

# PostgreSQL users
postgresql_superuser_name: postgres
postgresql_superuser_password: password
postgresql_replication_user: replicator
postgresql_replication_password: password
postgresql_replication_auth_method: md5

# PostgreSQL params
postgresql_max_connections: 100
postgresql_shared_buffers: 256MB
postgresql_wal_level: replica
postgresql_shared_preload_libraries: "pg_stat_statements, auto_explain"

# Additional PostgreSQL params (optional)
postgresql_custom_parameters:
  max_worker_processes: 8
  max_wal_senders: 10
  wal_keep_segments: 32

# Additional pg_hba.conf rules (optional)
# postgresql_additional_pg_hba:

# PgBouncer params
pgbouncer_listen_port: 6432

# HAProxy params
haproxy_config: "/etc/haproxy/haproxy.cfg"

# Cluster variables
cluster_vip_1: "192.168.64.100"

# Prometheus settings
prometheus_retention: "30d"
prometheus_storage_path: "/var/lib/prometheus"
prometheus_config_path: "/etc/prometheus"

# Grafana settings
grafana_admin_password: "admin"

# Common paths and ports for exporters
node_exporter_port: 9100
postgres_exporter_port: 9187
prometheus_port: 9090
grafana_port: 3000
