- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Create HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config }}"
    mode: '0644'

- name: Enable and start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true
    daemon_reload: true
