---
- name: Install and configure HAProxy
  hosts: haproxy
  become: true
  vars:
    haproxy_config: "/etc/haproxy/haproxy.cfg"
    postgres_port: 5432
    patroni_port: 8008

  tasks:
    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: true

    - name: Create HAProxy configuration
      ansible.builtin.template:
        src: templates/haproxy.cfg.j2
        dest: "{{ haproxy_config }}"
        mode: '0644'
      notify: Restart HAProxy

    - name: Enable and start HAProxy
      ansible.builtin.systemd:
        name: haproxy
        state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: Restart HAProxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
