---
- name: Установка Patroni-кластера
  hosts: promoters
  become: true
  vars:
    pg_version: 16
    data_dir: "/var/lib/postgresql/{{ pg_version }}/main"
    patroni_config: "/etc/patroni.yml"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3-pip
          - python3-psycopg2
          - etcd
          - wget
          - gnupg
        update_cache: yes

    - name: Adding GPG-key PostgreSQL
      ansible.builtin.shell: |
        wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | tee /etc/apt/trusted.gpg.d/postgresql.asc
      args:
        creates: /etc/apt/trusted.gpg.d/postgresql.asc

    - name: Adding apt repository PostgreSQL
      ansible.builtin.apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
        state: present
        filename: "pgdg"

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install PostgreSQL {{ pg_version }}
      apt:
        name: postgresql-{{ pg_version }}
        state: present

    - name: Install patroni
      pip:
        name: patroni[etcd]

    - name: Stop PostgreSQL
      service:
        name: postgresql
        state: stopped
        enabled: no

    - name: Clean data_dir
      file:
        path: "{{ data_dir }}"
        state: absent

    - name: Create config Patroni
      template:
        src: patroni.yml.j2
        dest: /etc/patroni.yml
        mode: '0644'

    - name: Set owner of data directory PostgreSQL
      file:
        path: "{{ data_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'
        recurse: yes

    - name: Clean previous state of etcd
      file:
        path: /var/lib/etcd
        state: absent
      when: clean_etcd is defined and clean_etcd

    - name: Create directory for etcd data
      file:
        path: /var/lib/etcd
        state: directory
        owner: etcd
        group: etcd
        mode: '0700'

    - name: Stop etcd if running
      systemd:
        name: etcd
        state: stopped
      ignore_errors: true

    - name: Generate etcd config
      template:
        src: templates/etcd.conf.yml.j2
        dest: /etc/etcd.yml
        mode: '0644'

    - name: Install systemd unit for etcd
      template:
        src: files/etcd.service.j2
        dest: /etc/systemd/system/etcd.service
        mode: '0644'

    - name: Restart etcd
      systemd:
        name: etcd
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Start etcd on first node
      when: inventory_hostname == "patroni1"
      block:
        - name: Start etcd on first node
          systemd:
            name: etcd
            daemon_reload: yes
            enabled: yes
            state: started

    - name: Wait for first etcd node will start
      wait_for:
        host: "{{ ansible_host }}"
        port: 2379
        timeout: 30

    - name: Wait for the first node to be ready
      when: inventory_hostname != "patroni1"
      wait_for:
        host: "{{ hostvars['patroni1']['ansible_host'] }}"
        port: 2379
        timeout: 30

    - name: Launching other etcd nodes
      when: inventory_hostname != "patroni1"
      systemd:
        name: etcd
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Wait for cluster formation
      shell: |
        timeout 30 bash -c 'until etcdctl --endpoints=http://{{ ansible_host }}:2379 cluster-health; do sleep 5; done'
      register: cluster_health
      until: cluster_health.rc == 0
      retries: 10
      delay: 5

    - name: Check cluster state
      shell: |
        etcdctl --endpoints=http://{{ ansible_host }}:2379 member list
      register: etcd_members
      changed_when: false

    - name: Create patroni logs directory
      file:
        path: /var/log/patroni
        state: directory
        mode: '0755'

    - name: Create systemd unit for Patroni
      template:
        src: files/patroni.service.j2
        dest: /etc/systemd/system/patroni.service
        mode: '0644'

    - name: Create config for patroni logrotate
      copy:
        dest: /etc/logrotate.d/patroni
        mode: '0644'
        content: |
          /var/log/patroni/patroni.log {
              daily
              rotate 7
              compress
              delaycompress
              missingok
              notifempty
              create 0640 postgres postgres
          }

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Patroni systemd unit
      systemd:
        name: patroni
        state: started
        enabled: yes
