#---
#- name: Install keepalived
#  apt:
#    name: keepalived
#    state: present
#    update_cache: true
#
#- name: Configure keepalived
#  template:
#    src: keepalived.conf.j2
#    dest: /etc/keepalived/keepalived.conf
#    mode: '0644'
#    owner: root
#    group: root
#  notify: restart keepalived
#
#- name: Make script executable
#  file:
#    path: /usr/local/bin/check_haproxy.sh
#    mode: '0755'
#    state: file
#
#- name: Ensure keepalived is enabled and started
#  systemd:
#    name: keepalived
#    state: started
#    enabled: true

---

- name: Install jq
  ansible.builtin.apt:
    name: jq
    state: present

- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    allow_downgrade: true
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  environment: "{{ proxy_env | default({}) }}"

- name: Create directory /opt/etc/keepalived
  ansible.builtin.file:
    path: /opt/etc/keepalived
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create directory /opt/keepalived/scripts
  ansible.builtin.file:
    path: /opt/keepalived/scripts
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create vrrp_script
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      /bin/kill -0 `cat /run/haproxy/haproxy.pid`
    dest: /opt/keepalived/scripts/haproxy_check.sh
    owner: root
    group: root
    mode: "0700"
  notify: "Restart keepalived"

- name: Generate keepalived conf file
  when: add_balancer is not defined or not add_balancer|bool
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: "Restart keepalived"

- name: Generate check scripts for keepalived
  become: true
  with_items:
    - f: files/chk_patroni_leader.sh
      d: /opt/keepalived/scripts
  ansible.builtin.template:
    src: '{{ item.f }}'
    dest: '{{ item.d }}'
    mode: '0755'
    owner: root
    group: root

- name: Block for tasks with balancer
  when: add_balancer is defined and add_balancer|bool
  block:  # for add_balancer.yml
    - name: "Fetch keepalived.conf conf file from {{ groups.promoters[0] }}"
      run_once: true
      ansible.builtin.fetch:
        src: /etc/keepalived/keepalived.conf
        dest: files/keepalived.conf
        validate_checksum: true
        flat: true
      delegate_to: "{{ groups.promoters[0] }}"

    - name: Copy keepalived.conf conf file to replica
      ansible.builtin.copy:
        src: files/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        mode: "0644"
      notify: "Restart keepalived"

    - name: Remove keepalived.conf file from localhost
      become: false
      run_once: true
      ansible.builtin.file:
        path: files/keepalived.conf
        state: absent
      delegate_to: localhost

    - name: Prepare keepalived.conf conf file (replace "interface")
      ansible.builtin.lineinfile:
        path: /etc/keepalived/keepalived.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: true
      loop:
        - { regexp: '^.*interface', line: '   interface {{ vip_interface }}' }
      loop_control:
        label: "{{ item.line }}"
      notify: "Restart keepalived"
