---
- name: Install jq via apt
  ansible.builtin.apt:
    name: jq
    state: present

- name: Install keepalived via apt
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Create directory /opt/etc/keepalived
  ansible.builtin.file:
    path: /opt/etc/keepalived
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create directory /opt/keepalived/scripts
  ansible.builtin.file:
    path: /opt/keepalived/scripts
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create vrrp_script
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      /bin/kill -0 `cat /var/run/haproxy.pid`
    dest: /opt/keepalived/scripts/haproxy_check.sh
    owner: root
    group: root
    mode: "0700"
  notify: "Restart keepalived"

- name: Add execution rights to haproxy_check.sh
  ansible.builtin.file:
    path: /opt/keepalived/scripts/haproxy_check.sh
    mode: 'u+x'

- name: Generate keepalived conf file
  when: add_balancer is not defined or not add_balancer|bool
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: "Restart keepalived"

- name: Generate check scripts for keepalived
  become: true
  with_items:
    - f: files/chk_patroni_leader.sh
      d: /opt/keepalived/scripts
  ansible.builtin.template:
    src: '{{ item.f }}'
    dest: '{{ item.d }}'
    mode: '0755'
    owner: root
    group: root

- name: Ensure logrotate is installed
  ansible.builtin.apt:
    name: logrotate
    state: present

- name: Configure rsyslog for keepalived
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/keepalived.conf
    content: |
      if $programname == 'keepalived' then /var/log/keepalived.log
      & stop
    owner: root
    group: root
    mode: '0644'

- name: Create logrotate configuration for keepalived
  ansible.builtin.copy:
    dest: /etc/logrotate.d/keepalived
    content: |
      /var/log/keepalived.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          create 0640 root root
          sharedscripts
          postrotate
              systemctl reload keepalived > /dev/null 2>/dev/null || true
          endscript
      }
    owner: root
    group: root
    mode: '0644'

- name: Ensure keepalived logs to /var/log/keepalived.log
  ansible.builtin.lineinfile:
    path: /etc/keepalived/keepalived.conf
    regexp: '^log_file'
    line: 'log_file /var/log/keepalived.log'
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Enable and start keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true
    daemon_reload: true
