scope: demo
name: patroni3

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.64.4:8008

etcd:
  hosts: 192.168.64.2:2379,192.168.64.3:2379,192.168.64.4:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      password: postgres
      options:
        - superuser
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 192.168.64.4:5432
  data_dir: /var/lib/postgresql/16/main
  bin_dir: /usr/lib/postgresql/16/bin
  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: replicator
      password: replicator
  parameters:
    max_connections: 100
    shared_buffers: 256MB
    wal_level: replica
    hot_standby: "on"
    shared_preload_libraries: 'pg_stat_statements, auto_explain'
  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: 100M
    checkpoint: fast
  pg_hba:
    - host replication replicator 192.168.64.0/24 trust
    - host all all 0.0.0.0/0 trust
